import streamlit as st
from PIL import Image
img = Image.open(r'one.jpg')
img2 = Image.open(r'two.jpg')
img3 = Image.open(r'thre.jpg')
img4 = Image.open(r'four.jpg')
img5 = Image.open(r'five.jpg')
img6 = Image.open(r'six.jpg')
print(type(img))
st.title('Команда МФТИ Естественный интеллект')
st.text('Наша команда')
st.image(img, width = 200 )
st.image(img2, width = 200 )
st.image(img3, width = 200 )
st.image(img4, width = 200 )
st.image(img5, width = 200 )
st.image(img6, width = 200 )
st.text('Наша команда')
